# CITADEL configuration
[docker-id]
DOCKER_13 = ab96a5f6b2664
DOCKER_12 = 1ebf17d092e8
DOCKER_11 = 41ff30192a087e
DOCKER_10 = 23903af1fbf21
DOCKER_9  = e4e8a81ce36
DOCKER_8  = ff23ea5fc3e7
DOCKER_7  = 7ae7d3396118
DOCKER_6 = 96ec9d884f0d
DOCKER_5 = 4ad0687d1aef
DOCKER_4  = c8d40daa6cd5
DOCKER_3  = 5115613e837d
DOCKER_2  = b2943f581c82
DOCKER_1  = bbdbde200dae

[root_dir]
# the dir of CITADEL.conf
dir_name=/data/zxy/DL_compiler_test/1_test_code/CITADEL/CITADEL/tensorflow