# CITADEL configuration
[docker-id]
DOCKER_13 = 5c2df2034d
DOCKER_12 = 02d2b847ec
# torch11 is our default environment
DOCKER_10 = 25fef3bd5c
DOCKER_9  = 4e0777511d
DOCKER_8  = 1106016281
DOCKER_7  = bca4e43fca

[root_dir]
# the dir of CITADEL.conf
dir_name=/data/zxy/DL_compiler_test/1_test_code/CITADEL/CITADEL/pytorch